version: '2'
services:

   node:
     build:
       context: ./docker/
       dockerfile: nodedockerfile
     image: node1
     volumes:
       - ./redis:/opt/node_redisproject
     expose:
        - "3000"
     tty: true

     links:
        - redis
     environment:
        - REDIS_PORT=tcp://redis:6379
        
   redis:
     build:
       context: ./docker/
       dockerfile: redisdockerfile
     image: redis1
     tty: true
     expose:
        - "6379"
